// Generated by https://quicktype.io

export interface Sorteios {
  id?:        number;
  imagem:    string;
  titulo:    string;
  estado:    string;
  descricao: string;
  data:      number;
  valor: number;
  count_rifas: number;

}
